[package]
name = "ml-service"
version = "0.1.0"
authors = ["Hiroki Mizukami <piroyoung.m@gmail.com>"]
edition = "2018"

[dependencies]
grpc = "0.6.2"
protobuf = "2.8.2"

[build-dependencies]
protoc-rust-grpc = "0.6.2"
