[package]
name = "ml-service"
version = "0.1.0"
authors = ["Hiroki Mizukami <piroyoung.m@gmail.com>"]
edition = "2018"
publish = false

[[bin]]
name = "main"
path = "src/main.rs"

[dependencies]
tonic = "0.1.1"
prost = "0.6.1"

[build-dependencies]
tonic-build = "0.1.1"
